package com.jkamsker.modemsim.monitor;

public enum EventType {
    SESSION_START,
    SESSION_STOP,
    RX_BYTES,
    TX_BYTES,
    PARSED_COMMAND,
    PARSE_ERROR,
    HANDLER_RESULT,
    SCHEDULER_ENQUEUE,
    SCHEDULER_EMIT,
    STATE_CHANGE,
    MACRO_DECISION,
    MACRO_EVENT,
    FAULT_TRIGGERED,
    INJECTION,
    POLICY_DENIED,
    VALIDATION_ERROR,
    AUDIT_FAILURE,
    REPLAY_MARKER,
    PORT_OPEN_FAILED,
    PORT_LOST,
    RX_OVERFLOW,
    TX_OVERFLOW,
    DROPPED_EVENTS
}
