package com.jkamsker.modemsim.monitor;

public enum EventType {
    SESSION_START,
    SESSION_STOP,
    RX_BYTES,
    TX_BYTES,
    PARSED_COMMAND,
    HANDLER_RESULT,
    SCHEDULER_ENQUEUE,
    SCHEDULER_EMIT,
    STATE_CHANGE,
    MACRO_DECISION,
    FAULT_TRIGGERED,
    INJECTION,
    AUDIT_FAILURE,
    REPLAY_MARKER,
    PORT_LOST,
    RX_OVERFLOW,
    TX_OVERFLOW
}
